# Generated by Django 4.1.2 on 2022-11-10 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=20)),
                ('periodo', models.CharField(max_length=20)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('N', 'Prefiro não declarar')], max_length=1)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('matricula', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefone', models.CharField(max_length=11, unique=True)),
                ('tipo_pessoa', models.CharField(choices=[('N', 'Núcleo de Apoio ao Educando'), ('A', 'Aluno'), ('P', 'Professor'), ('S', 'Secretario')], max_length=1)),
                ('turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_estilo_aprendizagem.turma')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
