# Generated by Django 4.1.2 on 2022-11-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
