# Generated by Django 4.1.2 on 2022-11-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0002_alter_usuario_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now=True)),
                ('questao_1', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_2', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_3', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_4', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_5', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_6', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_7', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_8', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_9', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_10', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_11', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_12', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_13', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_14', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_15', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_16', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_17', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_18', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_19', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('questao_20', models.CharField(blank=True, choices=[('A', 'Resposta: A'), ('B', 'Resposta: B')], max_length=1, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_estilo_aprendizagem.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='turma',
            name='escola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_estilo_aprendizagem.escola'),
        ),
    ]
