# Generated by Django 4.1.2 on 2022-11-22 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0003_escola_formulario_turma_escola'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_estilo_aprendizagem.usuario'),
        ),
        migrations.CreateModel(
            name='Analises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percepcao', models.TextField()),
                ('entrada', models.TextField()),
                ('processamento', models.TextField()),
                ('entendimento', models.TextField()),
                ('formulario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_estilo_aprendizagem.formulario')),
            ],
        ),
    ]
