# Generated by Django 4.1.2 on 2022-12-19 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0005_remove_analises_entendimento_remove_analises_entrada_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analises',
            old_name='turma',
            new_name='usuario_turma',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='turma',
        ),
    ]
