# Generated by Django 4.1.2 on 2022-12-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0006_rename_turma_analises_usuario_turma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_estilo_aprendizagem.turma'),
        ),
    ]
