# Generated by Django 4.1.2 on 2022-12-20 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0008_remove_analises_analise_entendimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='usuario_nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_estilo_aprendizagem.usuario'),
        ),
        migrations.AlterField(
            model_name='analises',
            name='usuario_turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_estilo_aprendizagem.turma'),
        ),
        migrations.AlterField(
            model_name='form_atual',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_estilo_aprendizagem.usuario'),
        ),
        migrations.AlterField(
            model_name='form_atual',
            name='analises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='app_estilo_aprendizagem.analises'),
        ),
    ]
