# Generated by Django 4.1.2 on 2022-12-20 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_estilo_aprendizagem', '0009_alter_analises_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analises',
            name='usuario_turma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='app_estilo_aprendizagem.turma'),
        ),
    ]
